import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#d9d9d9",
  },
  container: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  contentCard: {
    width: "100%",
    backgroundColor: "#d9d9d9",
    maxWidth: 1400,
    alignSelf: "center",
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  topRightArea: {
    alignItems: "flex-end",
    gap: 6,
  },
  menuButton: {
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 6,
  },
  menuButtonText: {
    fontSize: 36,
    lineHeight: 36,
    color: "#7a7a7a",
    fontWeight: "700",
  },
  titleBlock: {
    gap: 4,
  },
  logoPlaceholder: {
    width: 160,
    borderWidth: 1,
    borderColor: "#b3b3b3",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  logoText: {
    color: "#6e6e6e",
    fontSize: 11,
  },
  dateField: {
    minWidth: 160,
  },
  title: {
    fontSize: 30,
    fontWeight: "700",
    color: "#1f1f1f",
  },
  subtitle: {
    color: "#7f7f7f",
    fontSize: 14,
  },
  formGrid: {
    marginTop: 8,
    gap: 8,
  },
  cols3: {
    flexDirection: "row",
  },
  cols2: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cols1: {
    flexDirection: "column",
  },
  formColumn: {
    flex: 1,
    minWidth: 280,
    gap: 8,
  },
  fieldCard: {
    borderWidth: 1,
    borderColor: "#b7b7b7",
    borderRadius: 12,
    backgroundColor: "#d9d9d9",
    padding: 8,
  },
  cardTitle: {
    color: "#e01919",
    fontSize: 18,
    fontWeight: "700",
    borderBottomWidth: 1,
    borderBottomColor: "#bbbbbb",
    paddingBottom: 4,
    marginBottom: 6,
  },
  label: {
    marginTop: 4,
    marginBottom: 4,
    fontSize: 14,
    fontWeight: "600",
    color: "#1f1f1f",
  },
  input: {
    borderWidth: 1,
    borderColor: "#bdbdbd",
    borderRadius: 999,
    backgroundColor: "#e6e6e6",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
  },
  optionsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  option: {
    borderWidth: 1,
    borderColor: "#bdbdbd",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#e6e6e6",
  },
  optionSelected: {
    backgroundColor: "#d04044",
    borderColor: "#d04044",
  },
  optionText: {
    color: "#1f1f1f",
    fontSize: 13,
  },
  optionTextSelected: {
    color: "#ffffff",
  },
  volumeBox: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  volumeLabel: {
    fontSize: 14,
    fontWeight: "600",
  },
  volumeValue: {
    borderWidth: 1,
    borderColor: "#bdbdbd",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
    minWidth: 90,
    textAlign: "center",
    backgroundColor: "#e6e6e6",
    fontWeight: "700",
  },
  helperText: {
    marginTop: 4,
    color: "#828282",
    fontSize: 12,
  },
  footer: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  athleteField: {
    flex: 1,
    maxWidth: 360,
  },
  button: {
    backgroundColor: "#d04044",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  coachContainer: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 24,
    minHeight: "100%",
  },
  coachTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  coachTitle: {
    marginTop: 16,
    marginBottom: 10,
    fontSize: 50,
    fontWeight: "700",
    color: "#121212",
    textDecorationLine: "underline",
  },
  coachSectionTitle: {
    color: "#e01919",
    fontSize: 40,
    fontWeight: "700",
    marginBottom: 8,
  },
  coachSpinner: {
    marginVertical: 8,
  },
  coachError: {
    color: "#b91c1c",
    fontWeight: "700",
    marginBottom: 8,
  },
  coachEmpty: {
    color: "#444",
    marginBottom: 8,
  },
  coachCardsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  coachCard: {
    flexGrow: 1,
    flexBasis: 240,
    minHeight: 240,
    borderWidth: 1,
    borderColor: "#c2c2c2",
    borderRadius: 12,
    backgroundColor: "#fff",
    padding: 10,
  },
  coachCardHeader: {
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d1d1",
    paddingBottom: 6,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: "700",
  },
  coachCardMuted: {
    fontSize: 11,
    color: "#666",
    marginBottom: 6,
  },
  coachCardText: {
    fontSize: 12,
    color: "#161616",
    fontWeight: "600",
    lineHeight: 19,
  },
  coachFooter: {
    marginTop: 16,
    alignItems: "flex-end",
  },
  sidebarOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    flexDirection: "row",
  },
  sidebarBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  sidebar: {
    width: 320,
    maxWidth: "86%",
    backgroundColor: "#f2f2f2",
    paddingTop: 16,
    paddingHorizontal: 18,
    borderLeftWidth: 1,
    borderLeftColor: "#d0d0d0",
  },
  sidebarBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 22,
  },
  sidebarLogoMark: {
    width: 46,
    height: 46,
    borderRadius: 999,
    backgroundColor: "#d04044",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarLogoMarkText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700",
  },
  sidebarBrandText: {
    flex: 1,
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
  },
  sidebarItem: {
    borderTopWidth: 1,
    borderTopColor: "#7e7e7e",
    paddingVertical: 12,
  },
  sidebarItemText: {
    fontSize: 34,
    color: "#121212",
    fontWeight: "500",
  },
});
